version: '2'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    build: 
      context: .
      dockerfile: dockerfile.yml
    command: stdbuf -o L roscore
    volumes:
      - ${PWD}:/root/catkin_ws/src/anomaly_detection
    networks:
      - ros
    restart: unless-stopped
  ros-visualizer:
    image: osrf/ros:melodic-desktop-full
    container_name: ros-visualizer
    depends_on:
      - ros-master
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    #share your user to the container in order to access your x11
    user: 1000:1000 #adapt as needed!
    volumes:
      #share your x11 socket and permissions to the container
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/etc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /home/nicof:/home/nicof:rw #share your home with write permissions
    command: rqt
