FROM osrf/ros:melodic-desktop-full

# RUN sudo ./opt/ros/melodic/setup.sh
COPY ./kairos_ws-robot_b_work/src/summit_packages/deb ./tmp/deb
RUN cd /tmp/deb && ./install_debs.sh
# RUN cd ~/catkin_ws/
# RUN catkin_make