version: '2'

# Reminder:
# - Change the home directory to your own

# Containers orchestration
services:
  ros-master:
    build: 
      context: .
      dockerfile: dockerfile_master.yml
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: unless-stopped
  ros-visualizer:
    build:
      context: .
      dockerfile: dockerfile.yml
    container_name: ros-visualizer
    depends_on:
      - ros-master
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
    #share your user to the container in order to access your x11
    user: 1000:1000 #adapt as needed!
    volumes:
      #share your x11 socket and permissions to the container
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/etc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /home/nicof:/home/nicof:rw #share your home with write permissions
      # - ${PWD}:/home/nicof/catkin_ws/src/anomaly_detection:rw
    command: rqt

# Network configuration
networks:
  ros:
    driver: bridge