arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot_arm_waist_joint
    - robot_arm_shoulder_joint
    - robot_arm_elbow_joint
    - robot_arm_forearm_roll_joint
    - robot_arm_wrist_angle_joint
    - robot_arm_wrist_rotate_joint
  constraints:
    goal_time: 1
    stopped_velocity_tolerance: 0.02

gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot_arm_left_finger_joint
