port: /dev/ttyDXL

joint_order: [robot_arm_waist_joint, robot_arm_shoulder_joint, robot_arm_elbow_joint, robot_arm_forearm_roll_joint, robot_arm_wrist_angle_joint, robot_arm_wrist_rotate_joint, robot_arm_gripper_joint]
sleep_positions: [0, -1.85, 1.55, 0, 0.8, 0, 0]

joint_state_publisher:
  update_rate: 100
  publish_states: true
  topic_name: joint_states

groups:
  arm: [robot_arm_waist_joint, robot_arm_shoulder_joint, robot_arm_elbow_joint, robot_arm_forearm_roll_joint, robot_arm_wrist_angle_joint, robot_arm_wrist_rotate_joint]

# Blue fixed by Interbotix driver
grippers: 
  robot_arm_gripper_joint:
    horn_radius: 0.022
    arm_length: 0.036
    left_finger: robot_arm_left_finger_joint
    right_finger: robot_arm_right_finger_joint

shadows:
  robot_arm_shoulder_joint:
    shadow_list: [robot_arm_shoulder_shadow]
    calibrate: true
  robot_arm_elbow_joint:
    shadow_list: [robot_arm_elbow_shadow]
    calibrate: true

sisters:

motors:
  robot_arm_waist_joint:
    ID: 1
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  robot_arm_shoulder_joint:
    ID: 2
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 1
    Velocity_Limit: 131
    Min_Position_Limit: 841
    Max_Position_Limit: 2867
    Secondary_ID: 255

  robot_arm_shoulder_shadow_joint:
    ID: 3
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 841
    Max_Position_Limit: 2867
    Secondary_ID: 2

  robot_arm_elbow_joint:
    ID: 4
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 1
    Velocity_Limit: 131
    Min_Position_Limit: 898
    Max_Position_Limit: 3094
    Secondary_ID: 255

  robot_arm_elbow_shadow_joint:
    ID: 5
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 898
    Max_Position_Limit: 3094
    Secondary_ID: 4

  robot_arm_forearm_roll_joint:
    ID: 6
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  robot_arm_wrist_angle_joint:
    ID: 7
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 1
    Velocity_Limit: 131
    Min_Position_Limit: 830
    Max_Position_Limit: 3504
    Secondary_ID: 255

  robot_arm_wrist_rotate_joint:
    ID: 8
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  robot_arm_gripper_joint:
    ID: 9
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255
